# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "01_deck.ipynb",
         "MyCard": "02_mycard.ipynb"}

modules = ["card.py",
           "deck.py",
           "mycard.py"]

doc_url = "https://nitinverma78.github.io/deck_of_cards/"

git_url = "https://github.com/nitinverma78/deck_of_cards/tree/master/"

def custom_doc_links(name): return None
